# Generated by Django 4.2.6 on 2023-10-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.CharField(default='', max_length=360),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=20, verbose_name='Nom Produit'),
        ),
    ]
