# Generated by Django 4.2.6 on 2023-10-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bools', '0002_alter_produit_description_alter_produit_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(default='', max_length=228),
            preserve_default=False,
        ),
    ]
