# Generated by Django 4.2.6 on 2023-10-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bools', '0004_alter_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
    ]
