# Generated by Django 4.2.7 on 2023-11-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bools', '0007_panier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='panier_date',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='statut',
        ),
        migrations.AddField(
            model_name='article',
            name='panier_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
